### ISSUE TITLE
渡したリストを元に補完するUIを追加したい

### ISSUE THREAD

**Issue by maripiyoko** [oneteam-dev/oneteam-rte-kt#1]
https://github.com/oneteam-dev/comuque-android/issues/646#issuecomment-388702027

- oneteam-rte ライブラリの更新など #2
- [x] メンションのためのユーザーリストを渡すインターフェイスを実装 #3
- ~補完のUIはJS側で実装~ -> oneteam-rte側で実装済み

**Comment by maripiyoko** [comment]
## node ビルドツールインストール

https://github.com/oneteam-dev/oneteam-rte-kt#development

```
npm install && npm run build
```

エラー発生
nodeバージョンをlatestに上げる

2018-05-16時点

```
$ nodebrew ls-remote
...
v9.10.0   v9.10.1   
v9.11.0   v9.11.1   
v10.0.0   
v10.1.0
...
```


安定版のインストール
```
$ nodebrew install-binary stable
```

安定版を使用
```
$ nodebrew use stable                                                                                                                                      use v10.0.0
```

error

```
ERROR in ./~/oneteam-rte/lib/plugins/prism/languages.js
Module not found: Error: Can't resolve 'prismjs/components/prism-jade' in '/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/oneteam-rte/lib/plugins/prism'
 @ ./~/oneteam-rte/lib/plugins/prism/languages.js 101:0-40
 @ ./~/oneteam-rte/lib/plugins/prism/index.js
 @ ./~/oneteam-rte/lib/plugins/index.js
 @ ./~/oneteam-rte/lib/RichTextEditor.js
 @ ./~/oneteam-rte/lib/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! oneteam-rte-kt-internal@1.0.0 build: `npm run clean && webpack --optimize-minimize && npm run jade`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the oneteam-rte-kt-internal@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by maripiyoko** [comment]
```
$ nodebrew install-binary v8.9.4
$ nodebrew use v8.9.4
$ node -v
```

更新がたくさんありそうなので一気に依存更新
https://qiita.com/kurosame/items/0434d81bdcd97eb0da19#%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%82%92%E6%9C%80%E6%96%B0%E3%81%AB%E3%81%99%E3%82%8B

```
npm install -g npm-check-updates
npm-check-updates -u // package.jsonのパッケージを全て最新にして上書く
npm update // package.jsonに記載してあるバージョンに更新する
npm install
```

### パッケージ更新リスト

```
$ npm-check-updates -u 

 oneteam-rte                  1.0.2  →     2.1.2 
 react                      ^15.4.2  →   ^16.3.2 
 react-dom                  ^15.4.2  →   ^16.3.2 
 babel-eslint                ^7.1.1  →    ^8.2.3 
 babel-loader               ^6.2.10  →    ^7.1.4 
 babel-preset-power-assert   ^1.0.0  →    ^2.0.0 
 css-loader                 ^0.26.1  →  ^0.28.11 
 eslint                     ^3.14.0  →   ^4.19.1 
 eslint-plugin-babel         ^4.0.1  →    ^5.1.0 
 eslint-plugin-react         ^6.9.0  →    ^7.8.2 
 jsdom                       ^9.4.2  →  ^11.10.0 
 mocha                       ^3.0.2  →    ^5.1.1 
 style-loader               ^0.13.1  →   ^0.21.0 
 stylus-loader               ^2.3.1  →    ^3.0.2 
 webpack                     ^2.2.0  →    ^4.8.3 
 webpack-dev-server          ^2.2.0  →    ^3.1.4 
 babel-polyfill           ^6.22.0  →  ^6.26.0 
 babel-cli                ^6.22.2  →  ^6.26.0 
 babel-preset-react       ^6.22.0  →  ^6.24.1 
 react-addons-test-utils  ^15.4.2  →  ^15.6.2 
```

## 実行

```
 npm run build
```

エラー

```
+ webpack-cli@2.1.3
added 266 packages in 22.76s
Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
    at Object.get [as UglifyJsPlugin] (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack/lib/webpack.js:165:10)
    at Object.<anonymous> (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/webpack.config.babel.js:17:24)
    at Module._compile (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at loader (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/bin/webpack.js:240:39)
    at Object.parse (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/bin/webpack.js:218:8
    at Object.<anonymous> (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at runCommand.then.result (/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/webpack/bin/webpack.js:62:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oneteam-rte-kt-internal@1.0.0 build: `npm run clean && webpack --optimize-minimize && npm run jade`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oneteam-rte-kt-internal@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by maripiyoko** [comment]
別のエラー

```
ERROR in ./node_modules/htmlclean/lib/htmlclean.js
Module not found: Error: Can't resolve './pathdata' in '/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/htmlclean/lib'
 @ ./node_modules/htmlclean/lib/htmlclean.js 23:13-34
 @ ./node_modules/draft-js-oneteam-rte-plugin/lib/encoding/convertContentStateToHTML/index.js
 @ ./node_modules/oneteam-rte/es/encoding/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/htmlclean/lib/htmlclean.js
Module not found: Error: Can't resolve './phrasing-elements' in '/Users/mariko/workspace/heartrails/projects/oneteam/oneteam-rte-kt/node_modules/htmlclean/lib'
 @ ./node_modules/htmlclean/lib/htmlclean.js 21:24-54
 @ ./node_modules/draft-js-oneteam-rte-plugin/lib/encoding/convertContentStateToHTML/index.js
 @ ./node_modules/oneteam-rte/es/encoding/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.css 7:619-670
 @ ./node_modules/font-awesome/css/font-awesome.css
 @ ./node_modules/react-fa/lib/index.js
 @ ./node_modules/react-oneteam/es/Avatar/index.js
 @ ./node_modules/react-oneteam/es/index.js
 @ ./node_modules/oneteam-rte/es/plugins/mention/components/MentionSuggestionsEntry/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.css 7:528-580
 @ ./node_modules/font-awesome/css/font-awesome.css
 @ ./node_modules/react-fa/lib/index.js
 @ ./node_modules/react-oneteam/es/Avatar/index.js
 @ ./node_modules/react-oneteam/es/index.js
 @ ./node_modules/oneteam-rte/es/plugins/mention/components/MentionSuggestionsEntry/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.css 7:435-488
 @ ./node_modules/font-awesome/css/font-awesome.css
 @ ./node_modules/react-fa/lib/index.js
 @ ./node_modules/react-oneteam/es/Avatar/index.js
 @ ./node_modules/react-oneteam/es/index.js
 @ ./node_modules/oneteam-rte/es/plugins/mention/components/MentionSuggestionsEntry/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/react-oneteam/es/LoadingIcon/loading-sprites.png
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/react-oneteam/es/LoadingIcon/index.js 22:59-91
 @ ./node_modules/react-oneteam/es/index.js
 @ ./node_modules/oneteam-rte/es/plugins/mention/components/MentionSuggestionsEntry/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot
Module parse failed: Unexpected character '�' (1:1)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.css 7:325-368
 @ ./node_modules/font-awesome/css/font-awesome.css
 @ ./node_modules/react-fa/lib/index.js
 @ ./node_modules/react-oneteam/es/Avatar/index.js
 @ ./node_modules/react-oneteam/es/index.js
 @ ./node_modules/oneteam-rte/es/plugins/mention/components/MentionSuggestionsEntry/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0
Module parse failed: Unexpected character '�' (1:1)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.css 7:248-299
 @ ./node_modules/font-awesome/css/font-awesome.css
 @ ./node_modules/react-fa/lib/index.js
 @ ./node_modules/react-oneteam/es/Avatar/index.js
 @ ./node_modules/react-oneteam/es/index.js
 @ ./node_modules/oneteam-rte/es/plugins/mention/components/MentionSuggestionsEntry/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js

ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" standalone="no"?>
| <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
| <svg>
 @ ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.css 7:713-764
 @ ./node_modules/font-awesome/css/font-awesome.css
 @ ./node_modules/react-fa/lib/index.js
 @ ./node_modules/react-oneteam/es/Avatar/index.js
 @ ./node_modules/react-oneteam/es/index.js
 @ ./node_modules/oneteam-rte/es/plugins/mention/components/MentionSuggestionsEntry/index.js
 @ ./node_modules/oneteam-rte/es/RichTextEditor.js
 @ ./node_modules/oneteam-rte/es/index.js
 @ ./js/editor.js
 @ ./js/index.js
 @ multi babel-polyfill ./js/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! oneteam-rte-kt-internal@1.0.0 build: `npm run clean && webpack --mode development --optimize-minimize && npm run jade`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the oneteam-rte-kt-internal@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by maripiyoko** [comment]
`1.2.0` でリリースされたのでクローズします。
